---
title: "Criterion behaviour"
author: "B. Charnomordic"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
vignette: >
  %\VignetteIndexEntry{a title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,echo=TRUE,message=FALSE, warning=FALSE}
  library(geozoning)
```


# 2D map simulation 
## 
#########################
#Step 1: generate map 
#########################
#A map object is simulated with a Gaussian field and a variogram model. 450 points are randomly allocated on a square field of size 1.Then 1936 points are kriged on a regular grid using inverse distance weighted interpolation. A Delaunay tesselation yields point neighborhood in the sense of Voronoi.

```{r,echo=TRUE,message=FALSE, warning=FALSE,fig.height=10}
  seed=10
  map=genMap(DataObj=NULL,seed=seed,disp=FALSE,krig=1)
  ro=loopQ3(map,step=0.1,disp=0,QUIET=T)
  # ro is a matrix sorted by reverse order of crit. It has 8 columns and 56 rows. Columns contain the following values calculated for each quantile vector:  criterion, cost, cost per label, number of zones, quantile associated probability values and number of non degenerated quantiles. Each row corresponds to the best zoning obtained for the corresponding quantile at the end of the correction procedure. To save time and memory, details are not saved.
  # run correctionTree procedure for best zoning and save results
  bqProb=ro[1,5:7]
  criti=correctionTree(bqProb,map,SAVE=TRUE)
  res=searchNODcrit1(bqProb,criti)
  b=res$ind[[1]][1]
  K=criti$zk[[2]][[b]]
  bZ=K$zonePolygone
  dispZ(map$step,map$krigGrid,zonePolygone=bZ)
  # distance matrix has high values, criterion is the smallest one (6.417), distance between zones 5 and 7
  bmd=criti$mdist[[2]][[b]] 
  # run correctionTree procedure for worst zoning and save results
  wqProb=ro[56,5:7]
  criti=correctionTree(wqProb,map,SAVE=TRUE)
  res=searchNODcrit1(wqProb,criti)
  w=res$ind[[1]][1]
  K=criti$zk[[2]][[w]]
  wZ=K$zonePolygone
  dispZ(map$step,map$krigGrid,zonePolygone=wZ)
  # distance matrix has some low values, criterion is the smallest one (3.747), distance between zones 1 and 2
  wmd=criti$mdist[[2]][[w]]
```


# Session informations
```{r session,echo=FALSE,message=FALSE, warning=FALSE}
  sessionInfo()
```

