---
title: "Zoning simulated data"
author: "B. Charnomordic"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
vignette: >
  %\VignetteIndexEntry{a title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,echo=TRUE,message=FALSE, warning=FALSE}
  library(geozoning)
```


# 2D map simulation 
## 
#########################
#Step 1: generate map 
#########################
#A map object is simulated with a Gaussian field and a variogram model. 450 points are randomly allocated on a square field of size 1.Then 1936 points are kriged on a regular grid using inverse distance weighted interpolation. A Delaunay tesselation yields point neighborhood in the sense of Voronoi.

```{r,echo=TRUE,message=FALSE, warning=FALSE,fig.height=10}
  seed=80
  map=genMap(DataObj=NULL,seed=seed,disp=FALSE,krig=2,Vmean=15)
  
  # display 2D map with three different views: first one=kriged data, second one=contour lines, third one=raw data.
  plotMap(map)
  # The map object contains all components required for zoning generation, evaluation and visualization. The data-related components include the kriged data, grid resolution, size in each dimension and map boundary. Kriged data are available as a SpatialPointsDataFrame object, as well as a matrix object directly usable by image functions. rawData are stored as well in the map object, for traceability purposes. The neighborhood-related components include the list of neighbor point indices for each kriged data point, as well as the areas of Voronoi polygons associated to all points. Finally the variogram-related components include the VGM model used to simulate the field, as well as the equivalent RandomFields model.
  # Check the mean and standard deviation of generated data.
  meanvarSimu(map)
```

```{r,echo=TRUE,message=FALSE, warning=FALSE}
   ################################################################
   # step 2 - generate zoning from map for a given probability vector 
   ################################################################
   # Given a probability vector, a vector of values is obtained using the quantile function.
   qq=quantile(map$krigGrid,na.rm=TRUE,prob=c(0.5,0.7))
   # display map image with contour levels corresponding to qq values
   dispZ(map$step,map$krigGrid,valQ=qq)
   #A zoning is done on the kriged data, by computing the contour lines corresponding to the vector of values given by the probability vector, trimming them to the map boundary and defining zones corresponding to the closed contour lines.
   # A zoning is a list of SpatialPolygons objects. It does not contain data, only polygon geometry.
   ZK=initialZoning(c(0.5,0.7),map) # names(ZK)  "resCrit"  "resDist" "resZ" "cL" "qProb"
   # initialZoning calls zoneGeneration, calNei, calDistance, calCrit
   # zoneGeneration calls contourAuto
   # contourAuto calls contourLines and extensionLine 
   # plot zoning (12 zones in this case)
   K=ZK$resZ
   Z=K$zonePolygone
   plotZ(Z)
   # or more detailed plot - compare it to previous plot of contour lines
   # we see that contour lines are now extended to the map boundary in order to close zones and that contour lines impossible to close or yielding zones with 0 or 1 point are removed. 
    dispZ(map$step,map$krigGrid,zonePolygone=Z)
   # Outline boundaries of zone 3
   dispZ(map$step,map$krigGrid,zonePolygone=Z,iZ=3)
   # Outline all polygons of zone 3- It contains 4 polygons
   linesSp(Z[[3]],col="blue") # first one in blue
   linesSp(Z[[3]],k=2,col="red") # second one in red, and so on
   # A zone can have one or several holes, and each hole is an independent zone.zone 3 has 3 holes (zones 9, 10, 11). Due to its shape and to the common borders with the map boundary, zone 12 is not a hole in zone 3.
   holeSp(Z[[3]])
```

```{r,echo=TRUE,message=FALSE, warning=FALSE}
  # a more detailed plot: each zone is labelled with its number and its mean value
  dispZ(map$step,map$krigGrid,zonePolygone=Z,K=K,boundary=map$boundary,nbLvl=0,id=FALSE,mu=2) 
  title(paste(" q=[",toString(round(qq,2)),"]   crit=",round(ZK$resCrit,2),sep="")) # add quantile values and criterion value for Z.
  
  # print zone labels
  printLabZ(list(K))
  # print zone areas
  printZsurf(K$zonePolygone)
  # print zone ids
  printZid(Z)
  # remove zones with less than 5 data points
  K=calNei(Z,map$krigData,map$krigSurfVoronoi,map$krigN,nmin=10)
  plotZ(K$zonePolygone)

```

```{r,echo=TRUE,message=FALSE, warning=FALSE}
  ################################################################
  # step 3 - Generate tree of possible corrections for small zones 
  # (remove, i.e. merge into englobing zone, r grow - if grow, isolated zone -> grows bigger   
  # but remains isolated from others (distIsoZ parameter) - non isolated zone -> joins closest zone with same labels
  ################################################################
  criti<-correctionTree(c(0.4,0.7),map,SAVE=TRUE,ALL=TRUE,LASTPASS=FALSE,distIsoZ=0.001)#save all branches resulting from correction steps
# a small value of distIsoZ ensures that zones 7 and 8 have place to grow.
  zk=criti$zk

#   # here 2 small zones (#7 and #8), hence 3 levels (level 1 is initial zoning, level 2 has 2 branches, level 3 has 4 branches.
#   # for each correction step-first branch=zone removal, second   branch=zone junction, 
#   # the procedure starts with the smallest zone, here zone #7.
   Z21=zk[[2]][[1]]$zonePolygone
   Z22=zk[[2]][[2]]$zonePolygone
   plotZ(Z21,id=TRUE) # result of removal of zone #7
   plotZ(Z22,id=TRUE) # result of growing of zone #7
   # then the correction procedure is done for zone #8 in these two zonings
   for (ii in 1:length(zk[[3]]))
   {
   plotZ(zk[[3]][[ii]]$zonePolygone) # result of removal of zone #8 in Z21
   }
   #successively:  removal of zone#8  in Z21, growing of zone#8  in Z21
   # removal of zone#8  in Z22, growing of zone#8  in Z22
   criti<-correctionTree(c(0.4,0.7),map,SAVE=TRUE,ALL=TRUE,LASTPASS=TRUE,distIsoZ=0.001)#other try with LASTPASS=TRUE removes at last step the zones that are still too small after all successive corrections
   # other run with ALL=FALSE saves memory by keeping only the first and the last levels
   criti<-correctionTree(c(0.4,0.7),map,SAVE=TRUE,ALL=FALSE,LASTPASS=FALSE,distIsoZ=0.001)



   
```


# Session informations
```{r session,echo=FALSE,message=FALSE, warning=FALSE}
  sessionInfo()
```

